5W2H
UnBArqDsw2024-2/2024.2_G7_Entrega_Entrega_01 pull request #17
Opened 2024-11-03 03:47 UTC by lipeaaraujo

Criação de um artefato utilizando uma adaptação do 5W2H, a fim de realizar definições sobre o projeto sob duas perspectivas: a dos desenvolvedores e clientes

## Tipos de mudanças

- [ ] Bugfix (mudança que não quebra a funcionalidade existente e corrige um problema)
- [ ] New feature (mudança que não quebra a funcionalidade existente e adiciona uma nova funcionalidade)
- [ ] Breaking change (mudança que pode fazer com que a funcionalidade existente não funcione como esperado)
- [ ] Documentation Update (se nenhuma das opções anteriores se aplicar)

## Checklist

- [ ] Eu li o documento CONTRIBUTING.md.
- [ ] Adicionei a documentação necessária (se aplicável).

2024-11-03 14:25 UTC, west7 approved these changes

2024-11-03 21:22 UTC, kalipassos requested changes
corrigir palavra "Respostas" que está como "Repostas" no histórico de versão. 

Na visão dos clientes (tabela 2) o "Por que?" precisaria englobar também clientes que vão retirar sua entrega na loja e estariam usando o app apenas pela praticidade de poder pedir online e buscar quando pronto.

2024-11-04 00:36 UTC, west7 approved these changes

2024-11-04 00:38 UTC, west7 approved these changes

2024-11-04 00:42 UTC, kalipassos approved these changes

2024-11-04 00:44 UTC, merged